[project]
name = "streamlit-app"
version = "0.2.0"
description = "A Streamlit-based Webapp for Machine Learning"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scikit-learn>=1.6.1",
    "streamlit>=1.45.0",
]
